apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie-application
  namespace: argocd
spec:
  project: mealie

  source:
    repoURL: https://github.com/RomanGrekov/mealie-argocd.git
    targetRevision: mealie-next
    path: argocd/overlays/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true