apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
spec:
  #storageClassName: ebs-sc
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi